### ISSUE TITLE
OMG！As a Java user, I'm not used to it.

### ISSUE THREAD

**Issue by houyuehai** [highcharts/highcharts-android#74] opened 2019-02-13 09:20 UTC
It's difficult to use.
eg：
      HIChart chart = new HIChart();
      chart.setType("line");
I think it should be：
      HIChart chart = new HIChart();
      chart.setType(HIChart.TYPE_LINE);
eg：
     yaxis2.labels.format = "{value:.,0f}";
I think it should be：
     yaxis2.labels.setFormat（new Callback｛
           public String call（value）｛
                return “”；
               ｝
       ｝）
I still see a lot of JS shadow.

**Comment by houyuehai** [comment] 2019-02-13 09:22
And the official example is version 6.0, not version 7.0.

**Comment by soommy12** [comment] 2019-02-13 10:33
Hi @houyuehai ! Yes, we are aware of that. The wrapper is constantly evolving and approaches you pointed are currently in works.
When it comes to examples - they are ready for version 7.0. We are waiting for the webmasters to put them on the site. Stay tuned!

**Comment by soommy12** [comment] 2019-02-13 10:39
Speaking of `labels.format` there are two ways to establish them. One, which you already pointed out and second which is called `labels.formatter`. This one takes the `HIFunction` object as parameter which let you do native callbacks as you want.

**Comment by houyuehai** [comment] 2019-02-14 06:44
Wow, today's official example has been updated to version 7.0. It's great. I am studying.

**Comment by MikolajMichalczak** [comment] 2024-05-14 14:05
It seems to be a duplicate of #46.

**Closed by MikolajMichalczak** 2024-05-14 14:05 UTC
Labels: Enhancement
