### ISSUE TITLE
Horizontal Scroll View

### ISSUE THREAD

**Issue by ASumIT2016** [highcharts/highcharts-android#22] opened 2018-09-17 10:53 UTC
how to set horizontal scroll view?

**Comment by ASumIT2016** [comment] 2018-09-24 11:35
sir please tell me how to set horizontal scroll view to highcharts-android.........?

**Comment by sebastianbochan** [comment] 2018-09-26 08:15
Hi @ASumIT2016,
I apologize for late reply. Currently, our Android developer is on vacation and will come back on Friday. He will contact you and answer for you questions.

Im sorry for inconvenience.

**Comment by soommy12** [comment] 2018-09-28 09:41
HI @ASumIT2016 ! I am really sorry for your waiting. To apply horizontal scroll view to your chart consider using `HIScrollablePlotArea`. Try to experiment with _minWidth_ value and choose the best fitting option for you app. Short example:
```
        HIChart chart = new HIChart();
        HIScrollablePlotArea scrollablePlotArea = new HIScrollablePlotArea();
        scrollablePlotArea.setMinWidth(1000);
        scrollablePlotArea.setScrollPositionX(1);
        chart.setScrollablePlotArea(scrollablePlotArea);
        options.setChart(chart);
```

**Comment by ASumIT2016** [comment] 2018-10-02 09:45
> HI @ASumIT2016 ! I am really sorry for your waiting. To apply horizontal scroll view to your chart consider using `HIScrollablePlotArea`. Try to experiment with _minWidth_ value and choose the best fitting option for you app. Short example:
> 
> ```
>         HIChart chart = new HIChart();
>         HIScrollablePlotArea scrollablePlotArea = new HIScrollablePlotArea();
>         scrollablePlotArea.setMinWidth(1000);
>         scrollablePlotArea.setScrollPositionX(1);
>         chart.setScrollablePlotArea(scrollablePlotArea);
>         options.setChart(chart);
> ```
@soommy12 
how to set scroll to y or y-axisposition?

**Comment by soommy12** [comment] 2018-10-02 10:17
At this moment there is no such option in Highcharts. As a workaround I suggest you to try setting chart height higher than the one in your xml. You should be able to find the best dimensions by changing `1000` to any needed value:
```
        HIChart chart = new HIChart();
        chart.setHeight(1000);
```
Additionally, if you consider your idea is worth implementing in the library core you can post it [here](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/filters/top).

**Comment by ASumIT2016** [comment] 2018-10-08 09:46
I want reload hicharts on same actitvity.?

**Comment by ASumIT2016** [comment] 2018-10-09 03:51
@soommy12 
i added search functionality in recycler view  after click on recylerview item ,i am opening activity contain hicharts. but problem is activity   not open with full screen. i am sending you an screen shot
![screenshot_1538544845](https://user-images.githubusercontent.com/26159831/46645886-ad74fb00-cba4-11e8-8952-0c623bb379ef.png)

**Comment by ASumIT2016** [comment] 2018-10-09 05:09
i reload hicharts, but problem is not clickable 
this my code 
plotOptions.getSeries().setEvents(new HIEvents());
        plotOptions.getSeries().getEvents().setClick(new HIFunction(
                f->{
                    Toast.makeText(this," First Clicked point [ "  + f.getProperty("index") + " ] ", Toast.LENGTH_SHORT).show();

                    //System.out.print("Column Index: "+f.getProperty("index"));
                    /*String index = String.valueOf(f.getProperty("index"));
                    getStatus(index);*/
                    //Log.d(TAG,"Column Index:: "+f.getProperty("index"));

                },
                new String[]{"index"}
        ));
---------------------------------------
first time its working but after reload its not work please help me.
thanks in adv.

**Comment by soommy12** [comment] 2018-10-09 07:07
In your new activity which contains `HIChartView` make sure to set _width_ and _height_ to _match_parent_. If you have set this already check if `chart.setHeight()` value (which was discussed earlier) is not too low. Please keep in mind that chart dimensions and whole `HIChartView` dimensions are two different things.

When it comes to your `HIFunction` implementation it's ok. I tested it and after chart reloading, it works as intended.

**Comment by sasikanth14** [comment] 2018-10-09 10:10
Can we make it horizontally scrollable if the graph is zoomed in? Right now enabling panning makes it possible but it requires two fingers swipe.

**Comment by ASumIT2016** [comment] 2018-10-10 04:04
> In your new activity which contains `HIChartView` make sure to set _width_ and _height_ to _match_parent_. If you have set this already check if `chart.setHeight()` value (which was discussed earlier) is not too low. Please keep in mind that chart dimensions and whole `HIChartView` dimensions are two different things.
> 
> When it comes to your `HIFunction` implementation it's ok. I tested it and after chart reloading, it works as intended.

chart.setHeight()
its working thanks.

**Comment by ASumIT2016** [comment] 2018-10-10 04:06
@soommy12 
i reload hicharts, but problem is not clickable
this my code
plotOptions.getSeries().setEvents(new HIEvents());
plotOptions.getSeries().getEvents().setClick(new HIFunction(
f->{
Toast.makeText(this," First Clicked point [ " + f.getProperty("index") + " ] ", Toast.LENGTH_SHORT).show();

            },
            new String[]{"index"}
    ));
first time its working but after reload its not work please help me.
help me for this...

**Comment by soommy12** [comment] 2018-10-10 07:46
@ASumIT2016 This is the right function to reload the chart. Your code fine too, I have already tested it. Which version of the library are you currently using?

**Comment by ASumIT2016** [comment] 2018-10-10 08:32
> @ASumIT2016 This is the right function to reload the chart. Your code is fine too, I have already tested it. Which version of the library are you currently using?

6.1.3

**Comment by ASumIT2016** [comment] 2018-10-16 03:59
> Here you are:
> 
> ```
>         Button btn = findViewById(R.id.btn);
>         HIChartView chartView = findViewById(R.id.hc);
>         HIOptions options = new HIOptions();
> 
>         HISpline series = new HISpline();
>         series.setName("Values");
>         series.setData(randData());
>         options.setSeries(new ArrayList<>(Collections.singletonList(series)));
> 
>         HIPlotOptions plotOptions = new HIPlotOptions();
>         plotOptions.setSeries(series);
>         plotOptions.getSeries().setEvents(new HIEvents());
>         plotOptions.getSeries().getEvents().setClick(new HIFunction(
>                 f->{
>                     Toast.makeText(this," First Clicked point [ " + f.getProperty("index") + " ] ", Toast.LENGTH_SHORT).show();
> 
>                 },
>                 new String[]{"index"}
>         ));
> 
>         chartView.setOptions(options);
> 
>         btn.setOnClickListener(new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
>                 chartView.reload();
>             }
>         });
> ```
> And the short video example of it:
> 
> ![example](https://user-images.githubusercontent.com/23573237/46730004-36fcf980-cc87-11e8-9917-f7c7026b6489.gif)
> 
> Although, please remember that index is not the point index in that case. This refers to chart's series array, it returns 0 because there is only one element in it (only one series). If you want to get point data you should do something like this:
> 
> ```
>         plotOptions.getSeries().setPoint(new HIPoint());
>         plotOptions.getSeries().getPoint().setEvents(new HIEvents());
>         plotOptions.getSeries().getPoint().getEvents().setClick(new HIFunction(
>                 f->{
>                     Toast.makeText(
>                             this,
>                             "Clicked point: [" + f.getProperty("x") + ", " + f.getProperty("y")+ " ]",
>                             Toast.LENGTH_SHORT)
>                             .show();
>                 },
>                 new String[]{"x", "y"}
>         ));
> ```

hi @soommy12 actual my data is dynamic . 
i still get problem to click chart.

**Comment by soommy12** [comment] 2018-10-16 12:28
What does it mean your data is dynamic? As this question no longer applies to the issue title ("Horizontal Scroll View") I suggest you close this one to avoid a mess and open a new with detailed description and more code snippets to help me reproduce the problem.

**Comment by pradeep2424** [comment] 2018-12-03 06:43
> 
> 
> i reload hicharts, but problem is not clickable
> this my code
> plotOptions.getSeries().setEvents(new HIEvents());
> plotOptions.getSeries().getEvents().setClick(new HIFunction(
> f->{
> Toast.makeText(this," First Clicked point [ " + f.getProperty("index") + " ] ", Toast.LENGTH_SHORT).show();
> 
> ```
>             },
>             new String[]{"index"}
>     ));
> ```
> 
> first time its working but after reload its not work please help me.
> thanks in adv.


I am getting same issue. 
What is the solution to this issue.

**Closed** 2019-04-12 14:13 UTC
