### ISSUE TITLE
Can I work stably with AndroidX

### ISSUE THREAD

**Issue by ltma** [highcharts/highcharts-android#269] opened 2023-09-22 02:48 UTC
If Inscribe。The project needs to be migrated to Androidx. I would like to inquire if it can run stably on Androidx

**Comment by MikolajMichalczak** [comment] 2024-05-14 10:47
Thanks for the report. It seems to be a duplicate of #141. I'm closing this one and redirecting the discussion there. Please bear with us.

**Closed by MikolajMichalczak** 2024-05-14 10:47 UTC
Labels: Duplicate, Question
