### ISSUE TITLE
Needed V11.1.0 in highcharts-android same as highchart-ios and highchart-web

### ISSUE THREAD

**Issue by Nidhi2712** [highcharts/highcharts-android#267] opened 2023-07-20 09:39 UTC
We are using Highcharts on our Web,  iOS & Android platforms.

Web & iOS platforms are already in production with v11.1.0. 

Our top priority is to display the same chart throughout all platforms.

And I am developing for the Android platform but v11.1.0 is not available. Due to this, I am facing major Chart rendering-related issues. also, I have to get this development done in a limited timeline.

Please let me know when can I expect an update in highcharts-android with v11.1.0 support.

Thank you.

**Comment by soommy12** [comment] 2023-07-24 06:50
Hi there! The update is on its way and should be ready before the end of this week.

**Comment by Nidhi2712** [comment] 2023-07-31 12:15
Hi @soommy12 any update for this issue?

**Comment by soommy12** [comment] 2023-08-02 06:47
Hi @Nidhi2712 sorry, we encountered some problems during the release process. It's still in the works. Will let you know once we finish. Can you also tell me what precisely are you missing? Maybe there is a way of achieving your goals in the previous version of the library? In the meantime, we could advise you on that!

**Comment by shanselm-ergon** [comment] 2023-08-16 07:22
any update here?

**Comment by shanselm-ergon** [comment] 2023-08-28 06:32
Hello there, any update?

**Comment by Nidhi2712** [comment] 2023-08-29 04:21
Hi Stefan

We need to image of a chart view with high resolution so could you give us?

**Comment by shanselm-ergon** [comment] 2023-08-29 06:33
Hi @Nidhi2712 
I was expecting an answer from Highcharts regarding the release of the Android SDK v11. 
I would also like to update to the new version, but there is no v11 available. We produce a web/ios/android app, and we would like to keep the versions in sync. v11 is now available for a long time, but not for Android, so my question: when will the v11 be available for Android. A month ago, there were release problems, I hope they are fixed in the meantime.

**Comment by shanselm-ergon** [comment] 2023-09-14 07:37
Is there still no update on this issue? Highcharts 11 is out since April, why are we not getting an update for Android?

**Comment by Nidhi2712** [comment] 2023-09-16 12:31
We have the find another solution to resolve our issue. so now no any
update need in highchart.

Thank you.

**Comment by raf18seb** [comment] 2023-10-31 11:09
Hi!

I am truly very sorry for the inconvenience. Our Android developer has not been available recently. We are working on finding a replacement, but it might take some time. Once again, I'm sorry we reacted so late.

No ETA for v11 in Android for now, but we have targeted the issue and will try to solve it as soon as possible. I'll keep you updated.

**Comment by MikolajMichalczak** [comment] 2023-12-14 10:34
Hi! 
The good news - the latest release, version 11.2.0, is now available. Could you confirm if it meets your requirements? If so, we can consider closing this issue. Thank you for your patience.

**Comment by shanselm-ergon** [comment] 2023-12-21 08:47
Hi @MikolajMichalczak 
Thanks for the release. I just tried to update and found an issue but I don't know if the issue is, that the docs are outdated, or if the type is wrong (to me it might be the second one). 

https://api.highcharts.com/android/highcharts/com/highsoft/highcharts/common/hichartsclasses/HICSSObject.html
The color was a HiColor object until version 11. In the library it is now a string. If it should be a string, please update the docs AND define the format of the expected color string. If not, please provide a fix of the library. 

Thank you

**Comment by MikolajMichalczak** [comment] 2023-12-21 11:35
Thank you for your response @shanselm-ergon. You are right - color should now be a String in HICSSObject.

**Comment by shanselm-ergon** [comment] 2023-12-21 12:39
I will create a new one.

**Closed** 2024-03-05 12:31 UTC
