### ISSUE TITLE
Highchart not drawaing all the data

### ISSUE THREAD

**Issue by karthik-dusk** [highcharts/highcharts-android#138] opened 2020-02-21 10:25 UTC
What is the mistake in the below code, Highchart not drawaing all the data? 
I am setting the data dynamically, and setData() will be called whenever there is a new data. 
I have 7 series being set to options, but what I get to see is only 2 series plotted. To my surprise, sometimes I see wrong or improper data being set. 
I verified back the HIOptions in debug mode and see the data is being set properly.

What is that I am missing the below code? 

```
package hello.timelinechart;

import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.widget.RelativeLayout;

import com.highsoft.highcharts.common.HIColor;
import com.highsoft.highcharts.common.hichartsclasses.HIArea;
import com.highsoft.highcharts.common.hichartsclasses.HIChart;
import com.highsoft.highcharts.common.hichartsclasses.HICredits;
import com.highsoft.highcharts.common.hichartsclasses.HIExporting;
import com.highsoft.highcharts.common.hichartsclasses.HILabels;
import com.highsoft.highcharts.common.hichartsclasses.HILegend;
import com.highsoft.highcharts.common.hichartsclasses.HIMarker;
import com.highsoft.highcharts.common.hichartsclasses.HIOptions;
import com.highsoft.highcharts.common.hichartsclasses.HIPlotOptions;
import com.highsoft.highcharts.common.hichartsclasses.HITitle;
import com.highsoft.highcharts.common.hichartsclasses.HITooltip;
import com.highsoft.highcharts.common.hichartsclasses.HIXAxis;
import com.highsoft.highcharts.common.hichartsclasses.HIYAxis;
import com.highsoft.highcharts.core.HIChartView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import butterknife.BindView;
import butterknife.ButterKnife;

public class NewTimeLineChartView extends RelativeLayout {

    public static final double TRANSPARENCY = 0.75;

    @BindView(R2.id.highChart)
    HIChartView hiChartView;

    private Context mContext;
    private HIOptions mHiOptions = null;

    public NewTimeLineChartView(Context context, AttributeSet attrs) {
        super(context, attrs);
        mContext = context;
        ButterKnife.bind(this, (LayoutInflater.from(context).inflate(
                R.layout.new_time_line_chart_view, this, true)));
        init();
    }

    public void init() {
        initOptions();
        initChartSettings();
        initEmptyTitle();
        disableExportingOption();
        disableCreditsOptions();
        initYAxis();
        initToolTip();
        initPlotOptions();
        initLegend();
    }

    public void setData(Map<String, List<NewTimeLineChartModel.DateCount>> dataToChart) {
        List<String> xAxisLabels = new ArrayList<>();
        ArrayList<HIArea> seriesData = new ArrayList<>();

        if (dataToChart != null) {
            int position = 0;
            for (Map.Entry<String, List<NewTimeLineChartModel.DateCount>> entry : dataToChart.entrySet()) {
                String eventCode = entry.getKey();
                List<NewTimeLineChartModel.DateCount> dateCounts = entry.getValue();
                if (position == 0) xAxisLabels = getXAxislabesl(dateCounts);
                List<Number> yAxisData = new ArrayList<>();
                for (NewTimeLineChartModel.DateCount dateCount : dateCounts) {
                    yAxisData.add(dateCount.getValue());
                }
                NewTimeLineChartModel.Color color = getColorForPosition(position);
                seriesData.add(createArea(eventCode, color, color, color,  yAxisData.toArray(new Integer[yAxisData.size()])));
                position++;
            }
            initXAxisLabels(xAxisLabels.toArray(new String[xAxisLabels.size()]));
            mHiOptions.setSeries(new ArrayList<>(seriesData));
            hiChartView.setOptions(mHiOptions);
        }
    }

    private NewTimeLineChartModel.Color getColorForPosition(int position) {
        int color = Integer.parseInt(Integer.toHexString(ContextCompat.getColor(mContext,
                Utils.getColorCode(position)) & 0x00ffffff).toUpperCase(), 16);
        int r = (color >> 16) & 0xFF;
        int g = (color >> 8) & 0xFF;
        int b = (color >> 0) & 0xFF;
        NewTimeLineChartModel.Color colorToReturn = new NewTimeLineChartModel.Color(r, g, b);
        return colorToReturn;
    }

    private List<String> getXAxislabesl(List<NewTimeLineChartModel.DateCount> dateCounts) {
        List<String> xAxisLabels = new ArrayList<>();
        for (NewTimeLineChartModel.DateCount dateCount : dateCounts) {
            xAxisLabels.add(dateCount.getDate());
        }
        return xAxisLabels;
    }

    private HIArea createArea(String name, NewTimeLineChartModel.Color fillColor, NewTimeLineChartModel.Color lineColor, NewTimeLineChartModel.Color color, Number[] data) {
        HIArea hiArea = new HIArea();
        hiArea.setName(name);
        hiArea.setFillColor(HIColor.initWithRGBA(fillColor.red, fillColor.green, fillColor.blue, TRANSPARENCY));
        hiArea.setLineColor(HIColor.initWithRGBA(lineColor.red, lineColor.green, lineColor.blue, 1.0));
        HIMarker hiMarker = new HIMarker();
        hiMarker.setSymbol("circle");
        hiArea.setMarker(hiMarker);
        hiArea.setData(new ArrayList<>(Arrays.asList(data)));
        hiArea.setColor(HIColor.initWithRGBA(color.red, color.green, color.blue, 0.5));
        return hiArea;
    }

    private void initLegend() {
        HILegend hiLegend = new HILegend();
        hiLegend.setEnabled(false);
        mHiOptions.setLegend(hiLegend);
    }

    private void initPlotOptions() {
        HIPlotOptions plotOptions = new HIPlotOptions();
        plotOptions.setArea(new HIArea());
        plotOptions.getArea().setStacking("normal");
        plotOptions.getArea().setEnableMouseTracking(false);
        mHiOptions.setPlotOptions(plotOptions);
    }

    private void initToolTip() {
        HITooltip tooltip = new HITooltip();
        tooltip.setSplit(true);
        tooltip.setValueSuffix("");
        tooltip.setEnabled(false);
        mHiOptions.setTooltip(tooltip);
    }

    private void initYAxis() {
        HIYAxis yAxis = new HIYAxis();
        yAxis.setVisible(true);
        yAxis.setAllowDecimals(false);
        yAxis.setMaxPadding(0);
        yAxis.setTitle(new HITitle());
        yAxis.getTitle().setText("");
        yAxis.setLabels(new HILabels());
        yAxis.setOpposite(true);
        yAxis.setTickColor(HIColor.initWithHexValue("FFFFFF"));
        mHiOptions.setYAxis(new ArrayList<HIYAxis>() {{
            add(yAxis);
        }});
    }

    private void initXAxisLabels(String[] xAxisLabels) {
        HIXAxis xAxis = new HIXAxis();
        xAxis.setType("datetime");
        HILabels hiLabels = new HILabels();
        hiLabels.setRotation(0);
        setSteps(xAxisLabels, hiLabels);
        xAxis.setLabels(hiLabels);
        xAxis.setUnits(null);
        HITitle title = new HITitle();
        title.setText("");
        xAxis.setTitle(new HITitle());
        xAxis.setCategories(new ArrayList<>(Arrays.asList(xAxisLabels)));
        xAxis.setTickmarkPlacement("on");
        xAxis.setMaxPadding(0);
        xAxis.setShowLastLabel(true);
        xAxis.setShowFirstLabel(true);
        xAxis.setTickColor(HIColor.initWithHexValue("FFFFFF"));
        mHiOptions.setXAxis(new ArrayList<HIXAxis>() {{
            add(xAxis);
        }});
    }

    private void setSteps(String[] xAxisLabels, HILabels hiLabels) {
        int ticks = xAxisLabels.length;
        if (ticks < 7) {
            hiLabels.setStep(1);
        } else if (ticks == 7) {
            hiLabels.setStep(3);
        } else if (ticks > 7) {
            hiLabels.setStep(7);
        }
    }

    private void disableCreditsOptions() {
        HICredits hiCredits = new HICredits();
        hiCredits.setEnabled(false);
        mHiOptions.setCredits(hiCredits);
    }

    private void disableExportingOption() {
        HIExporting hiExporting = new HIExporting();
        hiExporting.setEnabled(false);
        mHiOptions.setExporting(hiExporting);
    }

    private void initEmptyTitle() {
        HITitle title = new HITitle();
        title.setText("");
        mHiOptions.setTitle(title);
    }

    private void initChartSettings() {
        HIChart hiChart = new HIChart();
        hiChart.setType("area");
        hiChart.setBackgroundColor(HIColor.initWithRGBA(255, 255, 255, 0.1));
        mHiOptions.setChart(hiChart);
    }

    private void initOptions() {
        mHiOptions = new HIOptions();
    }

}

```

**Comment by soommy12** [comment] 2020-02-21 11:38
Hi @karthik-dusk ! Thanks for your question. Can you please share where do you use your `setData()` method? How do you get new data set?

**Comment by karthik-dusk** [comment] 2020-02-24 04:22
setData() method will be called everytime when I receive an event from the WAMP. 

NewTimeLineChartModel.java
========================
```
package com.timelinechart;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class NewTimeLineChartModel {

    private ArrayList<String> xAxisLables = new ArrayList();
    private Map<String, StatusValue> yAxisData = new HashMap();

    public NewTimeLineChartModel() {
    }

    public ArrayList<String> getxAxisLables() {
        return xAxisLables;
    }

    public void setxAxisLables(ArrayList<String> xAxisLables) {
        this.xAxisLables = xAxisLables;
    }

    public Map<String, StatusValue> getyAxisData() {
        return yAxisData;
    }

    public void setyAxisData(Map<String, StatusValue> yAxisData) {
        this.yAxisData = yAxisData;
    }

    public static class StatusValue {
        String status;
        ArrayList<Number> values;

        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }

        public ArrayList<Number> getValues() {
            return values;
        }

        public void setValues(ArrayList<Number> values) {
            this.values = values;
        }
    }

    public static class Color {

        int red;
        int green;
        int blue;

        public Color(int red, int green, int blue) {
            this.red = red;
            this.green = green;
            this.blue = blue;
        }

        public int getRed() {
            return red;
        }

        public int getGreen() {
            return green;
        }

        public int getBlue() {
            return blue;
        }
    }

    public static class DateCount{
        String date;
        int value;

        public DateCount(String date, int value) {
            this.date = date;
            this.value = value;
        }

        public String getDate() {
            return date;
        }

        public void setDate(String date) {
            this.date = date;
        }

        public int getValue() {
            return value;
        }

        public void setValue(int value) {
            this.value = value;
        }
    }
}
```

**Comment by karthik-dusk** [comment] 2020-02-24 04:25
```
@Subscribe(threadMode = ThreadMode.MAIN)
    public void onEventMainThread(DataRefresh dataRefresh) {
NewTimeLineChartModel = // ... format the data the way charts accepts
setData(newTimeLineChartModel);
 }
```

**Comment by soommy12** [comment] 2020-02-25 08:36
That's behaviour is indeed strange. As from the Highcharts options setup code, everything seems to be ok. Did you try to print your data just before adding it to the new `HIArea` series? I mean, just before this line especially:

`hiArea.setData(new ArrayList<>(Arrays.asList(data)));`

**Comment by karthik-dusk** [comment] 2020-02-29 05:31
Yes.. I did verify the data being set. Yes, its a strange behavior, so I had to reach out to you.

**Comment by karthik-dusk** [comment] 2020-02-29 05:33
and I even read back the data from the charts, post setting it. To my surprise, before and after setting the data to the chart are matching. 
Let me further analyse.

**Comment by soommy12** [comment] 2020-03-03 14:52
Hi @karthik-dusk , did you manage to solve the problem? You can share a demo app for us so we can try to reproduce the problem if you wish.

**Comment by karthik-dusk** [comment] 2020-03-06 07:18
Thank you for following up, I appreciate it ..!
I will be working on this again today, was busy in some other thing so far.
I will keep you posted.

**Comment by karthik-dusk** [comment] 2020-03-09 06:24
@soommy12 Need your help here, I ran out all the options and tries. 
Will you be able to join the call?

**Comment by karthik-dusk** [comment] 2020-03-09 11:56
further retrying, 

When i do this, I see all the series plotted. but, when the same data is passed dynamically, I see only first 4 series set, I dont see last 2 series set.  

```
public void setTestData() {
        List<String> xAxisLabels = new ArrayList<>();
        xAxisLabels.addAll(Arrays.asList(new String[]{"a", "b", "c", "d", "e", "f", "g", "h", "i"}));

        initXAxisLabels(xAxisLabels.toArray(new String[xAxisLabels.size()]));

        ArrayList<HIArea> seriesData = new ArrayList<>();

        NewTimeLineChartModel.Color color = getColorForPosition(0);
        seriesData.add(createArea("one", color, color, color, new Number[]{984, 0, 0, 0, 1, 108, 0, 0, 0}));

        color = getColorForPosition(1);
        seriesData.add(createArea("two", color, color, color,new Number[]{316, 0, 0, 0, 1, 106, 2, 0, 1}));

        color = getColorForPosition(2);
        seriesData.add(createArea("three", color, color, color, new Number[]{214, 0, 0, 0, 25, 0, 2, 0, 2}));

        color = getColorForPosition(3);
        seriesData.add(createArea("four", color, color, color, new Number[]{212, 0, 0, 0, 30, 0, 0, 0, 0}));

        color = getColorForPosition(4);
        seriesData.add(createArea("five", color, color, color, new Number[]{128, 0, 0, 0, 28, 0, 0, 0, 0}));

        color = getColorForPosition(5);
        seriesData.add(createArea("six", color, color, color, new Number[]{126, 0, 0, 0, 28, 0, 0, 0, 0}));

        mHiOptions.setSeries(new ArrayList<>(seriesData));
        hiChartView.setOptions(mHiOptions);
        
    }
```

**Comment by soommy12** [comment] 2020-03-09 12:13
Hmm, okay. Gonna use your data and try to reproduce the problem.

**Comment by karthik-dusk** [comment] 2020-03-10 05:02
This is what I see, 

![what-i-c](https://user-images.githubusercontent.com/5618488/76281221-623faa00-62ba-11ea-80e6-68e5c21d414f.PNG)

This is what chart is suppose to show, 
![to-show](https://user-images.githubusercontent.com/5618488/76281256-7daab500-62ba-11ea-928f-70be4b3baf4e.PNG)

**Comment by karthik-dusk** [comment] 2020-03-11 06:40
any luck?

**Comment by soommy12** [comment] 2020-03-11 10:32
Not at all. Can you please share with us a working example?

**Comment by karthik-dusk** [comment] 2020-03-13 09:56
Sample Not-Working Code is here, 
https://github.com/karthik-dusk/highcharts-issue-android

Please check the logs when trying. 

**When you click on 1day button, I am drawing 4 series,** 
Chart: 
![image](https://user-images.githubusercontent.com/5618488/76609941-359bc480-653e-11ea-81cc-1889e8d0d2e5.png)

Logs: 
2020-03-13 15:17:53.189 17934-17934/com.karthik.highchartsdemo D/createArea: [984, 0, 0, 0, 1, 108, 0, 0, 0]
2020-03-13 15:17:53.190 17934-17934/com.karthik.highchartsdemo D/createArea: [316, 0, 0, 0, 1, 106, 2, 0, 1]
2020-03-13 15:17:53.190 17934-17934/com.karthik.highchartsdemo D/createArea: [214, 0, 0, 0, 25, 0, 2, 0, 2]
2020-03-13 15:17:53.191 17934-17934/com.karthik.highchartsdemo D/createArea: [212, 0, 0, 0, 30, 0, 0, 0, 0]

**When i click on "1 Week" button, I am drawing only 3 series, but I see 4 series plotted.** 
Chart: 
![image](https://user-images.githubusercontent.com/5618488/76610123-7693d900-653e-11ea-8569-7e1565d51c83.png)

Logs: 
2020-03-13 15:20:36.159 17934-17934/com.karthik.highchartsdemo D/createArea: [212, 0, 0, 0, 30, 0, 0, 0, 0]
2020-03-13 15:20:36.160 17934-17934/com.karthik.highchartsdemo D/createArea: [128, 0, 0, 0, 28, 0, 0, 0, 0]
2020-03-13 15:20:36.160 17934-17934/com.karthik.highchartsdemo D/createArea: [126, 0, 0, 0, 28, 0, 0, 0, 0]

When i click on "1 Month" button, I am drawing only 1 series, but I see 4 series being plotted. 
Chart: 
![image](https://user-images.githubusercontent.com/5618488/76610350-c96d9080-653e-11ea-8d56-12b419b13563.png)

Logs: 
2020-03-13 15:22:24.487 17934-17934/com.karthik.highchartsdemo D/createArea: [126, 0, 0, 0, 28, 0, 0, 0, 0]

APK is available here:

**Comment by karthik-dusk** [comment] 2020-03-13 10:01
APK is available here:
https://github.com/karthik-dusk/highcharts-issue-android/tree/master/HighChartsDemo/apks

**Comment by soommy12** [comment] 2020-03-13 11:27
Thank you very much for the demo app! We really appreciate that. Just wanted to ask something to be sure. The title says that the library doesn't draw all data but now you say it draws more than intended. Am I right?

**Comment by karthik-dusk** [comment] 2020-03-13 11:40
Yes, 
It is all about drawing new data, by completely removing old data. 
1. It is not drawing all the data 
2. It is not removing the old data before drawing new data.

**Comment by karthik-dusk** [comment] 2020-03-13 12:03
Introduced one more button "1 Year", On click of this, I am adding 6 series data, 
but I see only 4 series plotted. 

![image](https://user-images.githubusercontent.com/5618488/76619319-92a07600-6550-11ea-8794-b47cdff3bcd4.png)

code is committed to the repo as well. 

Code: 
 ```
if(duration.equalsIgnoreCase("year")) {

            Color color = getColorForPosition(0);
            seriesData.add(createArea("one", color, color, color, new Number[]{984, 0, 0, 0, 1, 108, 0, 0, 0}));

            color = getColorForPosition(1);
            seriesData.add(createArea("two", color, color, color, new Number[]{316, 0, 0, 0, 1, 106, 2, 0, 1}));

            color = getColorForPosition(2);
            seriesData.add(createArea("three", color, color, color, new Number[]{214, 0, 0, 0, 25, 0, 2, 0, 2}));

            color = getColorForPosition(3);
            seriesData.add(createArea("four", color, color, color, new Number[]{212, 0, 0, 0, 30, 0, 0, 0, 0}));

            color = getColorForPosition(4);
            seriesData.add(createArea("five", color, color, color, new Number[]{128, 0, 0, 0, 28, 0, 0, 0, 0}));

            color = getColorForPosition(5);
            seriesData.add(createArea("six", color, color, color, new Number[]{126, 0, 0, 0, 28, 0, 0, 0, 0}));
        }
```

**Comment by soommy12** [comment] 2020-03-13 12:05
Great! I'm currently investigating your code.

**Comment by soommy12** [comment] 2020-03-13 13:36
Ok, I've found the problem. Instead of:
```
mHiOptions.setSeries(new ArrayList<>(seriesData));
hiChart.setOptions(mHiOptions);
```

You should have:
```
HIOptions newOptions = mHiOptions;
newOptions.setSeries(seriesData);
hiChart.update(mHiOptions, false, true);
```

Although, during this investigation, I've found a little bug in the `update()` method. I've made a fix but the wrapper update will be released next week. Thank you for your report! Gonna ping you when fix will be introduced.

**Comment by karthik-dusk** [comment] 2020-03-13 16:04
hmmm ... but, this fix is not working :-( 
1. Charts are not rendering at all
2. Since 1 was not working, First time load I did, 
```
mHiOptions.setSeries(new ArrayList<>(seriesData));
hiChart.setOptions(mHiOptions);
```
subsequent loads, i did, 

```
HIOptions newOptions = mHiOptions;
newOptions.setSeries(seriesData);
hiChart.update(mHiOptions, false, true);
```
Yet, it did not work :-( 

Logs: 
```
2020-03-13 21:33:44.048 7185-7185/com.karthik.highchartsdemo E/HINativeController: com.highsoft.highcharts.common.hichartsclasses.HIOptions@1ce09a5
2020-03-13 21:33:44.049 7185-7185/com.karthik.highchartsdemo E/HINativeController: false
2020-03-13 21:33:44.049 7185-7185/com.karthik.highchartsdemo E/HINativeController: true
2020-03-13 21:33:44.065 7185-7185/com.karthik.highchartsdemo E/HIChartView: javascript:(function update(options, redraw, oneToOne) { chart.update(options, redraw, oneToOne); })(com.highsoft.highcharts.common.hichartsclasses.HIOptions@1ce09a5, false, true);
2020-03-13 21:33:44.071 7185-7185/com.karthik.highchartsdemo E/Highcharts: Uncaught SyntaxError: missing ) after argument list

```

**Comment by soommy12** [comment] 2020-03-13 16:14
Yes, it does not work at this moment. As I said, it will be working in the new release :)

**Comment by karthik-dusk** [comment] 2020-03-13 16:16
next release date please? will you be able to give a patch release for us immediately. 
Our release is blocking because of this issue.

**Comment by soommy12** [comment] 2020-03-16 08:21
Hi @karthik-dusk ! The decision was made, the fix will be released especially for the Android Wrapper in this week.

**Comment by karthik-dusk** [comment] 2020-03-18 05:55
Hi @soommy12, 
I want to understand one more thing. 
why is Hicharts have a permission to READ and WRITE to external storage?

**Comment by soommy12** [comment] 2020-03-18 07:05
To let you export your chart :)

**Comment by karthik-dusk** [comment] 2020-03-19 06:45
To export the chart, WRITE permission is sufficient right? what is the use of READ permission?

**Comment by soommy12** [comment] 2020-03-19 07:18
First, the chart image is saved into the device storage, then it is read from there to share :)

**Comment by karthik-dusk** [comment] 2020-03-23 06:27
hi @soommy12, waiting for the release, not sure if the release happened. 
Release was suppose to happen on Friday, 20th March 2020. 
I really don't know what is the status. 
When is it releasing? 
How to will be the release done? Will be part of global release or will it be a patch release only for us? 
Can I directly include in the gradle by changing the version?

**Comment by soommy12** [comment] 2020-03-23 06:41
Hello @karthik-dusk  , the new version of the library was released on the last Friday indeed. Please find it in the [release](https://github.com/highcharts/highcharts-android/releases) section.  Unfortunately, it will be available only as the downloadable aar version.

**Comment by karthik-dusk** [comment] 2020-03-23 09:55
This is seriously a problem, I was expecting this to be available in Gradle. I want this be used with Gradle. When will this be available to use from Gradle?

**Comment by soommy12** [comment] 2020-03-23 10:13
We're sorry but there is no ETA for gradle version atm.

**Comment by karthik-dusk** [comment] 2020-03-24 16:33
Hi @soommy12, This fix is not working :-(

**Comment by karthik-dusk** [comment] 2020-03-24 16:37
committed the code to the repo. 
https://github.com/karthik-dusk/highcharts-issue-android

**Comment by soommy12** [comment] 2020-03-25 07:52
Thanks for the demo code. We will check it out.

**Comment by karthik-dusk** [comment] 2020-03-26 08:54
In fact your sample code is not demonstrating the fix, It is not plotting multiple series of data. 

It has been more than a month now, I started to discuss on this issue from Feb 21, and today is March 26 and till now, there is no resolution of the issues reported. 

I have already mentioned, this issue is blocking our release.

**Comment by soommy12** [comment] 2020-03-26 09:37
We totally understand the problem. This issue is our priority at this moment. Please note that you mentioned many different problems in this ticket and the fix was introduced for the chart's `update` method which was not refreshing the number of series (old series was still visible when the `update()` method was triggered before the fix). We are investigating your sample code. Please stay tuned.

**Comment by karthik-dusk** [comment] 2020-03-26 09:43
Nope, there are not "many" issues.
I clearly mentioned, 
> It is not drawing all the data
> It is not removing the old data before drawing new data.

**Comment by soommy12** [comment] 2020-03-26 11:41
First of all, you're not setting the options for your chart (you can see that in the logs). Thus, you cannot update something that is not set yet, right? (this is what the second error stands for) You should put a setter into your `onCreate` method like this:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    hiChart = findViewById(R.id.hichart);
    init();
    setTestData("day");
    hiChart.setOptions(mHiOptions);
}
```
Then, to let your chart update all data (didn't see earlier that you're resetting the axes too), you should change the second flag to `true` like this:
```
HIOptions newOptions = mHiOptions;
newOptions.setSeries(seriesData);
hiChart.update(mHiOptions, true, true);
```

Please let me know if that helped. Looking forward to hearing your feedback!

**Comment by soommy12** [comment] 2020-03-30 09:39
Hello @karthik-dusk ! Did this solution meet your requirements? If yes, I would like to close the issue.

**Closed** 2020-04-02 08:34 UTC
Labels: bug

**Comment by karthik-dusk** [comment] 2020-04-03 16:17
Hi @soommy12 , After seeing the fix working, I was happy to include in my project. 
But, I am still facing problem in integrating ".aar" release to our project. Because, our project setup is such that, it does not support fat aar. 

described here: 
https://stackoverflow.com/questions/61015082/android-app-5-will-fail-to-load-the-external-dependency-1-declared-in-androi

I need a gradle fix instead of .aar fix.

**Comment by karthik-dusk** [comment] 2020-04-17 10:35
Hi @soommy12 , 

We are still facing some problem, attached are logs, please help. 
Please let me know, if you need more details, if logs are not sufficient. 

[logs.txt](https://github.com/highcharts/highcharts-android/files/4492375/logs.txt)

**Comment by karthik-dusk** [comment] 2020-04-28 05:35
Hi @soommy12 , Did you get a chance to have a look at this issue?

**Comment by soommy12** [comment] 2020-05-04 09:41
Hi @karthik-dusk ! The logs you posted are not an error. This is information what data is passed to the `HINativeController`. If you have any further question please submit another ticket.

**Comment by karthik-dusk** [comment] 2020-05-22 10:10
Is this fix, "Highchart not drawaing all the data", is available in 8.1.0 release? 
This fix was given exclusively for us in the from of .aar sometime back.

**Comment by soommy12** [comment] 2020-05-22 11:06
Yes, it is. We are currently working on the new release for the Android.

**Comment by karthik-dusk** [comment] 2020-05-29 06:16
Hi @soommy12 any tentative dates? please

**Comment by karthik-dusk** [comment] 2020-06-01 05:48
@soommy12 ??

**Comment by soommy12** [comment] 2020-06-01 06:25
Hi @karthik-dusk , we are planning the release in this week. Sorry, I didn't respond but this issue is already closed so I don't have the mentions enabled for it.

**Comment by soommy12** [comment] 2020-06-05 08:09
Hi @karthik-dusk ! The release has been scheduled for the next Monday
